/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace EchoRegistry {
  export type EchoStruct = {
    echoNoteId: string;
    parentNoteId: string;
    metadataUrl: string;
    echoBroadcaster: AddressLike;
    parentBroadcaster: AddressLike;
    timestamp: BigNumberish;
  };

  export type EchoStructOutput = [
    echoNoteId: string,
    parentNoteId: string,
    metadataUrl: string,
    echoBroadcaster: string,
    parentBroadcaster: string,
    timestamp: bigint
  ] & {
    echoNoteId: string;
    parentNoteId: string;
    metadataUrl: string;
    echoBroadcaster: string;
    parentBroadcaster: string;
    timestamp: bigint;
  };
}

export interface EchoRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATOR_SHARE"
      | "ECHO_FEE"
      | "PLATFORM_SHARE"
      | "checkIsEcho"
      | "echoCount"
      | "echoParent"
      | "echoesByParent"
      | "getEchoCount"
      | "getEchoFee"
      | "getEchoes"
      | "getParent"
      | "isEcho"
      | "owner"
      | "registerEcho"
      | "renounceOwnership"
      | "setTreasury"
      | "transferOwnership"
      | "treasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EchoRegistered"
      | "OwnershipTransferred"
      | "TreasuryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CREATOR_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ECHO_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "checkIsEcho", values: [string]): string;
  encodeFunctionData(functionFragment: "echoCount", values: [string]): string;
  encodeFunctionData(functionFragment: "echoParent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "echoesByParent",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEchoCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEchoFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getEchoes", values: [string]): string;
  encodeFunctionData(functionFragment: "getParent", values: [string]): string;
  encodeFunctionData(functionFragment: "isEcho", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerEcho",
    values: [string, string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CREATOR_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ECHO_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsEcho",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "echoCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "echoParent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "echoesByParent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEchoCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEchoFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEchoes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getParent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isEcho", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerEcho",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace EchoRegisteredEvent {
  export type InputTuple = [
    parentNoteId: string,
    echoNoteId: string,
    echoBroadcaster: AddressLike,
    parentBroadcaster: AddressLike,
    timestamp: BigNumberish,
    creatorPayment: BigNumberish,
    platformPayment: BigNumberish
  ];
  export type OutputTuple = [
    parentNoteId: string,
    echoNoteId: string,
    echoBroadcaster: string,
    parentBroadcaster: string,
    timestamp: bigint,
    creatorPayment: bigint,
    platformPayment: bigint
  ];
  export interface OutputObject {
    parentNoteId: string;
    echoNoteId: string;
    echoBroadcaster: string;
    parentBroadcaster: string;
    timestamp: bigint;
    creatorPayment: bigint;
    platformPayment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EchoRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EchoRegistry;
  waitForDeployment(): Promise<this>;

  interface: EchoRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATOR_SHARE: TypedContractMethod<[], [bigint], "view">;

  ECHO_FEE: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_SHARE: TypedContractMethod<[], [bigint], "view">;

  checkIsEcho: TypedContractMethod<[noteId: string], [boolean], "view">;

  echoCount: TypedContractMethod<[arg0: string], [bigint], "view">;

  echoParent: TypedContractMethod<[arg0: string], [string], "view">;

  echoesByParent: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, string, string, string, bigint] & {
        echoNoteId: string;
        parentNoteId: string;
        metadataUrl: string;
        echoBroadcaster: string;
        parentBroadcaster: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEchoCount: TypedContractMethod<[parentNoteId: string], [bigint], "view">;

  getEchoFee: TypedContractMethod<[], [bigint], "view">;

  getEchoes: TypedContractMethod<
    [parentNoteId: string],
    [EchoRegistry.EchoStructOutput[]],
    "view"
  >;

  getParent: TypedContractMethod<[echoNoteId: string], [string], "view">;

  isEcho: TypedContractMethod<[arg0: string], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerEcho: TypedContractMethod<
    [
      parentNoteId: string,
      echoNoteId: string,
      metadataUrl: string,
      parentBroadcaster: AddressLike
    ],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATOR_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ECHO_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkIsEcho"
  ): TypedContractMethod<[noteId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "echoCount"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "echoParent"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "echoesByParent"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, string, string, string, bigint] & {
        echoNoteId: string;
        parentNoteId: string;
        metadataUrl: string;
        echoBroadcaster: string;
        parentBroadcaster: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEchoCount"
  ): TypedContractMethod<[parentNoteId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEchoFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEchoes"
  ): TypedContractMethod<
    [parentNoteId: string],
    [EchoRegistry.EchoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParent"
  ): TypedContractMethod<[echoNoteId: string], [string], "view">;
  getFunction(
    nameOrSignature: "isEcho"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerEcho"
  ): TypedContractMethod<
    [
      parentNoteId: string,
      echoNoteId: string,
      metadataUrl: string,
      parentBroadcaster: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EchoRegistered"
  ): TypedContractEvent<
    EchoRegisteredEvent.InputTuple,
    EchoRegisteredEvent.OutputTuple,
    EchoRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;

  filters: {
    "EchoRegistered(string,string,address,address,uint256,uint256,uint256)": TypedContractEvent<
      EchoRegisteredEvent.InputTuple,
      EchoRegisteredEvent.OutputTuple,
      EchoRegisteredEvent.OutputObject
    >;
    EchoRegistered: TypedContractEvent<
      EchoRegisteredEvent.InputTuple,
      EchoRegisteredEvent.OutputTuple,
      EchoRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
  };
}
