/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EchoRegistry } from "./EchoRegistry";
export type { TippingPool } from "./TippingPool";
export type { VoiceNoteNFT } from "./VoiceNoteNFT";
